title: Weaponised Pasts
description: "Research project blog"

url: "https://jmartindale612.github.io"
baseurl: ""
                   # If this is a *project* site (username.github.io/repo), set baseurl: "/repo"
permalink: /news/:title/
markdown: kramdown
timezone: Europe/London
excerpt_separator: "<!-- more -->"

# Keep your repo tidy on GH Pages builds:
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - .vscode
  - README
  - LICENSE